<?xml version="1.0"?>
<package format="2">
  <name>scilab_optimization</name>
  <version>0.0.0</version>
  <description>The scilab_optimization package</description>

  <maintainer email="sch@robotis.com">sch</maintainer>
  <author email="sch@robotis.com">sch</author>

  <license>BSD</license>

  <!-- Build system -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Dependencies -->
  <build_depend>roscpp</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <exec_depend>roscpp</exec_depend>

  <export>
    <build_type>catkin</build_type>
  </export>
</package>
